### ISSUE TITLE
Export Smalltalk code to the exercism exercise directory

### ISSUE THREAD

**Issue by samWson** [exercism/exercism-pharo-tooling#1]
# User story
As a user, given that:
- I have completed my solution to an exercise

I want to:
- Export my code solution from the Pharo image into text files
- The text files should be in the exercise directory
- The text files should be ready to push to Exercism.io using the `exercism` command line tool

Related to this [issue](https://github.com/exercism/pharo/issues/1#issuecomment-396878025) and this [issue](https://github.com/exercism/pharo/issues/6).

# Description
Two files will need to be exported. One is untouched from the _file out_ process. It needs to stay this way to allow the code to _file in_ to another Pharo image. The second file will be scrubbed of machine readable artifacts and meta data for the sake of readability. This human readable file is what will be displayed on the Exercism.io website. The machine readable file will still need to be uploaded to Exercism.io, to enable other users to download and _file in_ the code to their image.

After the code has been exported from the Pharo image, the directory structure should look something like tree below assuming this is the Hello World exercise:
```
hello-world/
├── .ghost
│   ├── hello-world-test.st
│   └── hello-world.st
├── hello-world-test.st
└── hello-world.st
```
The files in the `.ghost` directory are the machine readable files. The directory is hidden because the code in them should never be edited outside a Pharo image, else they may no longer be machine readable. The directory is named `.ghost` for lack of a better name and can change later. The human readable files are in the root of the `hello-world` directory.

# Assumptions
- The directory structure will be created when the user enters `exercism fetch pharo <exercise-name>`
- The `*-test.st` files will be downloaded from Exercism.io when the `fetch` command is used

**Comment by macta** [comment]
I think we can close this issue now (and possibly close this repo - as we've got everything running in the standard exercism/pharo repo).

Aside - its interesting that your intuition of .ghost (at the top) was correct - we've ended up with a .pharo to dump the tonel output into for exercise submissions)

**Comment by samWson** [comment]
> Aside - its interesting that your intuition of .ghost (at the top) was correct - we've ended up with a .pharo to dump the tonel output into for exercise submissions)

I got the idea from Exercism's own guide for making language tracks. I think the term was more like `meta` or something similar that might clash with Smalltalk in a way.

I'll close this issue down now, and archive the repository.
