### ISSUE TITLE
Close this repo

### ISSUE THREAD

**Issue by macta** [exercism/exercism-pharo-tooling#5]
The tooling for pharo can happily live in /exercism/pharo so its probably confusing having a separate repo/issues?

**Comment by samWson** [comment]
@macta I'm happy with that. I'll close all the issues and PR's (all two of them), and archive the repo. I'll also leave a note on the README directing people to the [exercism/pharo](https://github.com/exercism/pharo) repository.

@kytrinyx just letting you know this repo has served its purpose. All of our tooling can happily co-exist in the language track repo.

**Comment by samWson** [comment]
Merged #6 to update the README. Closing and archiving now.
